# -*- coding: utf-8 -*-
# v1.3 game layer / weekly recap strings: English -> (de, fr, ja)
# Register matches the existing catalog: de "du", fr "vous", ja polite/gentle.

T = {
    "Secret badge": ("Geheimes Abzeichen", "Badge secret", "シークレットバッジ"),
    "Unlocked": ("Freigeschaltet", "Débloqué", "獲得済み"),
    "Locked": ("Gesperrt", "Verrouillé", "未獲得"),
    "ANCHOR PASS · %@": ("ANCHOR PASS · %@", "ANCHOR PASS · %@", "ANCHOR PASS · %@"),
    "Level %lld · %lld XP": ("Level %lld · %lld XP", "Niveau %lld · %lld XP", "レベル%lld · %lld XP"),
    "%lld XP to %@": ("Noch %lld XP bis %@", "Encore %lld XP avant %@", "あと%lld XPで%@"),
    "Top rank": ("Höchster Rang", "Rang maximal", "最高ランク"),
    "%lld-day streak": ("%lld-Tage-Serie", "Série de %lld jours", "%lld日連続"),
    "%lld/%lld badges": ("%lld/%lld Abzeichen", "%lld/%lld badges", "バッジ %lld/%lld"),

    # Badges
    "First Anchor": ("Erster Anker", "Première ancre", "はじめての錨"),
    "Finish your first Panic SOS session.": ("Beende deine erste Panic-SOS-Sitzung.", "Terminez votre première séance Panic SOS.", "初めてのPanic SOSセッションを完了"),
    "You faced it and stayed with it. That took courage.": ("Du hast dich gestellt und bist drangeblieben. Das braucht Mut.", "Vous y avez fait face sans lâcher prise. Cela demandait du courage.", "逃げずに向き合いました。それには勇気が必要でした。"),
    "Steady Hands": ("Ruhige Hände", "Mains sûres", "揺るがぬ手"),
    "Finish 3 Panic SOS sessions.": ("Beende 3 Panic-SOS-Sitzungen.", "Terminez 3 séances Panic SOS.", "Panic SOSセッションを3回完了"),
    "Three storms weathered. Your hands are steadier than you think.": ("Drei Stürme überstanden. Deine Hände sind ruhiger, als du denkst.", "Trois tempêtes traversées. Vos mains sont plus sûres que vous ne le pensez.", "3つの嵐を乗り越えました。あなたの手は思うよりずっと確かです。"),
    "Wave Rider": ("Wellenreiter", "Sur la vague", "波乗り"),
    "Finish 10 Panic SOS sessions.": ("Beende 10 Panic-SOS-Sitzungen.", "Terminez 10 séances Panic SOS.", "Panic SOSセッションを10回完了"),
    "Ten sessions. You know this water now.": ("Zehn Sitzungen. Du kennst dieses Wasser jetzt.", "Dix séances. Vous connaissez ces eaux, maintenant.", "10回のセッション。この海はもうよく知っています。"),
    "Storm Veteran": ("Sturmerprobt", "Vétéran des tempêtes", "嵐のベテラン"),
    "Finish 25 Panic SOS sessions.": ("Beende 25 Panic-SOS-Sitzungen.", "Terminez 25 séances Panic SOS.", "Panic SOSセッションを25回完了"),
    "Twenty-five times you chose to breathe through it.": ("Fünfundzwanzigmal hast du dich fürs Durchatmen entschieden.", "Vingt-cinq fois, vous avez choisi de respirer pour passer le cap.", "25回、呼吸で乗り切ることを選びました。"),
    "Lighthouse": ("Leuchtturm", "Phare", "灯台"),
    "Finish 50 Panic SOS sessions.": ("Beende 50 Panic-SOS-Sitzungen.", "Terminez 50 séances Panic SOS.", "Panic SOSセッションを50回完了"),
    "Fifty sessions. You're a light for your own ships.": ("Fünfzig Sitzungen. Du bist ein Licht für deine eigenen Schiffe.", "Cinquante séances. Vous êtes la lumière de vos propres navires.", "50回のセッション。あなたは自分の船を照らす光です。"),
    "Unsinkable": ("Unsinkbar", "Insubmersible", "沈まない心"),
    "Finish 100 Panic SOS sessions.": ("Beende 100 Panic-SOS-Sitzungen.", "Terminez 100 séances Panic SOS.", "Panic SOSセッションを100回完了"),
    "A hundred sessions. Nothing keeps you under.": ("Hundert Sitzungen. Nichts zieht dich mehr unter Wasser.", "Cent séances. Rien ne vous fait couler.", "100回のセッション。もう何にも沈められません。"),
    "Wave Breaker": ("Wellenbrecher", "Brise-lames", "防波堤"),
    "Lower your intensity by 3 or more in one session.": ("Senke deine Intensität in einer Sitzung um 3 oder mehr.", "Réduisez votre intensité de 3 points ou plus en une séance.", "1回のセッションで強さを3以上下げる"),
    "You watched a wave rise and fall. Proof that it passes.": ("Du hast eine Welle steigen und fallen sehen. Der Beweis, dass sie vorübergeht.", "Vous avez vu une vague monter puis retomber. La preuve que ça passe.", "波が高まり、引いていくのを見届けました。必ず過ぎ去るという証です。"),
    "Tide Turner": ("Gezeitenwender", "La marée tourne", "潮目を変える"),
    "Lower your intensity by 3 or more in 5 sessions.": ("Senke deine Intensität in 5 Sitzungen um 3 oder mehr.", "Réduisez votre intensité de 3 points ou plus sur 5 séances.", "5回のセッションで強さを3以上下げる"),
    "Five times the tide turned your way.": ("Fünfmal hat sich die Flut zu deinen Gunsten gewendet.", "Cinq fois, la marée a tourné en votre faveur.", "5回、潮目があなたの味方になりました。"),
    "Calm Engineer": ("Ruhe-Ingenieur", "Architecte du calme", "静けさの設計士"),
    "Lower your intensity by 3 or more in 20 sessions.": ("Senke deine Intensität in 20 Sitzungen um 3 oder mehr.", "Réduisez votre intensité de 3 points ou plus sur 20 séances.", "20回のセッションで強さを3以上下げる"),
    "Twenty big drops. You've built a method that works.": ("Zwanzig große Rückgänge. Du hast eine Methode gefunden, die funktioniert.", "Vingt fortes baisses. Vous avez bâti une méthode qui marche.", "20回の大きな改善。効果のある方法を自分で築きました。"),
    "Storm Tamer": ("Sturmbändiger", "Dompteur de tempêtes", "嵐を鎮める人"),
    "Bring an 8 or higher down to 4 or lower.": ("Bring eine 8 oder mehr auf 4 oder weniger.", "Faites passer un 8 ou plus à 4 ou moins.", "8以上の強さを4以下まで下げる"),
    "From an 8 to a 4. That isn't small. That's huge.": ("Von 8 auf 4. Das ist nicht klein. Das ist riesig.", "De 8 à 4. Ce n’est pas rien. C’est énorme.", "8から4へ。小さなことではありません。すごいことです。"),
    "Ten Calm Minutes": ("Zehn ruhige Minuten", "Dix minutes de calme", "穏やかな10分"),
    "Spend 10 minutes in Panic SOS sessions.": ("Verbringe 10 Minuten in Panic-SOS-Sitzungen.", "Passez 10 minutes en séances Panic SOS.", "Panic SOSセッションで合計10分過ごす"),
    "Ten minutes of practice on purpose. It adds up.": ("Zehn Minuten bewusstes Üben. Das summiert sich.", "Dix minutes de pratique volontaire. Tout compte.", "意識して10分練習しました。積み重ねが力になります。"),
    "The Calm Hour": ("Die ruhige Stunde", "L’heure du calme", "穏やかな1時間"),
    "Spend 60 minutes in Panic SOS sessions.": ("Verbringe 60 Minuten in Panic-SOS-Sitzungen.", "Passez 60 minutes en séances Panic SOS.", "Panic SOSセッションで合計60分過ごす"),
    "A full hour of breathing through it.": ("Eine ganze Stunde bewusstes Durchatmen.", "Une heure entière à respirer pour passer le cap.", "丸1時間、呼吸で乗り越えてきました。"),
    "Deep Water": ("Tiefes Wasser", "Eaux profondes", "深い海"),
    "Spend 3 hours in Panic SOS sessions.": ("Verbringe 3 Stunden in Panic-SOS-Sitzungen.", "Passez 3 heures en séances Panic SOS.", "Panic SOSセッションで合計3時間過ごす"),
    "Three hours of practice. Calm runs deep in you now.": ("Drei Stunden Übung. Die Ruhe reicht jetzt tief in dir.", "Trois heures de pratique. Le calme est profondément ancré en vous.", "3時間の練習。落ち着きがあなたの深くに根づいています。"),
    "Ripple": ("Erste Kreise", "Première onde", "さざ波"),
    "Reach a 3-day streak.": ("Erreiche eine 3-Tage-Serie.", "Atteignez une série de 3 jours.", "3日連続を達成"),
    "Three days in a row. The ripple starts here.": ("Drei Tage in Folge. Hier ziehen die ersten Kreise.", "Trois jours d’affilée. Tout commence par une onde.", "3日連続。ここからさざ波が広がります。"),
    "Full Week": ("Volle Woche", "Semaine complète", "まる1週間"),
    "Reach a 7-day streak.": ("Erreiche eine 7-Tage-Serie.", "Atteignez une série de 7 jours.", "7日連続を達成"),
    "Seven days of showing up for yourself.": ("Sieben Tage, an denen du für dich da warst.", "Sept jours à être là pour vous-même.", "7日間、自分のために向き合いました。"),
    "Fortnight Anchor": ("Zwei-Wochen-Anker", "Ancre de quinzaine", "2週間の錨"),
    "Reach a 14-day streak.": ("Erreiche eine 14-Tage-Serie.", "Atteignez une série de 14 jours.", "14日連続を達成"),
    "Two weeks. Your nervous system is learning.": ("Zwei Wochen. Dein Nervensystem lernt dazu.", "Deux semaines. Votre système nerveux apprend.", "2週間。あなたの神経系は学んでいます。"),
    "Moon Cycle": ("Mondzyklus", "Cycle lunaire", "月の満ち欠け"),
    "Reach a 30-day streak.": ("Erreiche eine 30-Tage-Serie.", "Atteignez une série de 30 jours.", "30日連続を達成"),
    "A whole moon cycle of calm practice.": ("Ein ganzer Mondzyklus voller Ruhe-Übung.", "Un cycle lunaire entier à pratiquer le calme.", "月がひと巡りするあいだ、落ち着きを練習しました。"),
    "Steady Current": ("Stete Strömung", "Courant régulier", "穏やかな潮流"),
    "Reach a 60-day streak.": ("Erreiche eine 60-Tage-Serie.", "Atteignez une série de 60 jours.", "60日連続を達成"),
    "Sixty days. This is who you are now.": ("Sechzig Tage. Das bist jetzt du.", "Soixante jours. C’est ce que vous êtes, désormais.", "60日。これが今のあなたです。"),
    "Hundred Tides": ("Hundert Gezeiten", "Cent marées", "百の潮"),
    "Reach a 100-day streak.": ("Erreiche eine 100-Tage-Serie.", "Atteignez une série de 100 jours.", "100日連続を達成"),
    "A hundred tides in and out. Remarkable.": ("Hundertmal Ebbe und Flut. Bemerkenswert.", "Cent marées, flux et reflux. Remarquable.", "100回の満ち引き。見事です。"),
    "Year of Calm": ("Ein Jahr Ruhe", "Une année de calme", "穏やかな1年"),
    "Reach a 365-day streak.": ("Erreiche eine 365-Tage-Serie.", "Atteignez une série de 365 jours.", "365日連続を達成"),
    "A full year. Take a bow.": ("Ein ganzes Jahr. Applaus für dich!", "Une année entière. Chapeau !", "まる1年。胸を張ってください。"),
    "First Check-In": ("Erster Check-in", "Premier bilan", "はじめてのチェックイン"),
    "Log your mood for the first time.": ("Trage zum ersten Mal deine Stimmung ein.", "Notez votre humeur pour la première fois.", "初めて気分を記録"),
    "Naming a feeling is the first step to taming it.": ("Ein Gefühl zu benennen ist der erste Schritt, es zu zähmen.", "Nommer une émotion, c’est le premier pas pour l’apprivoiser.", "気持ちに名前をつけることが、なだめる第一歩です。"),
    "Self-Aware": ("Achtsam", "Lucide", "自分を知る"),
    "Log 10 mood check-ins.": ("Trage 10 Stimmungs-Check-ins ein.", "Enregistrez 10 bilans d’humeur.", "気分のチェックインを10回記録"),
    "Ten check-ins. You're learning your own weather.": ("Zehn Check-ins. Du lernst dein eigenes Wetter kennen.", "Dix bilans. Vous apprenez à lire votre propre météo.", "10回のチェックイン。自分の心の天気がわかってきました。"),
    "Mood Mapper": ("Stimmungskartograf", "Cartographe des humeurs", "心の地図職人"),
    "Log 30 mood check-ins.": ("Trage 30 Stimmungs-Check-ins ein.", "Enregistrez 30 bilans d’humeur.", "気分のチェックインを30回記録"),
    "Thirty data points. Patterns are starting to show.": ("Dreißig Datenpunkte. Muster werden sichtbar.", "Trente points de données. Des tendances se dessinent.", "30のデータ。パターンが見えてきました。"),
    "Inner Weather": ("Inneres Wetter", "Météo intérieure", "心の天気"),
    "Log 100 mood check-ins.": ("Trage 100 Stimmungs-Check-ins ein.", "Enregistrez 100 bilans d’humeur.", "気分のチェックインを100回記録"),
    "A hundred check-ins. You read your skies like a pro.": ("Hundert Check-ins. Du liest deinen Himmel wie ein Profi.", "Cent bilans. Vous lisez votre ciel comme un pro.", "100回のチェックイン。心の空模様を読む達人です。"),
    "Year in Feelings": ("Ein Jahr Gefühle", "Une année d’émotions", "感情の1年"),
    "Log 365 mood check-ins.": ("Trage 365 Stimmungs-Check-ins ein.", "Enregistrez 365 bilans d’humeur.", "気分のチェックインを365回記録"),
    "A year of feelings, honestly noticed.": ("Ein Jahr voller Gefühle, ehrlich wahrgenommen.", "Une année d’émotions, accueillies avec sincérité.", "1年分の気持ちに、正直に向き合いました。"),
    "Bookends": ("Morgens & abends", "Matin et soir", "朝と夜"),
    "Check in both morning and evening on the same day.": ("Mach am selben Tag morgens und abends einen Check-in.", "Faites un bilan le matin et le soir du même jour.", "同じ日に朝と夜の両方でチェックイン"),
    "Morning and evening. You bookended your day.": ("Morgens und abends. Du hast deinen Tag eingerahmt.", "Matin et soir. Vous avez encadré votre journée.", "朝と夜。1日をしっかり締めくくりました。"),
    "Sunrise to Sunset": ("Von früh bis spät", "De l’aube au crépuscule", "日の出から日没まで"),
    "Check in morning and evening on 7 days.": ("Mach an 7 Tagen morgens und abends einen Check-in.", "Faites un bilan matin et soir pendant 7 jours.", "7日間、朝と夜にチェックイン"),
    "Seven full days, start to finish.": ("Sieben volle Tage, von Anfang bis Ende.", "Sept journées complètes, du début à la fin.", "まる7日間、朝から夜まで。"),
    "First Page": ("Erste Seite", "Première page", "最初のページ"),
    "Write your first journal entry.": ("Schreibe deinen ersten Tagebucheintrag.", "Écrivez votre première entrée de journal.", "初めてのジャーナルを書く"),
    "The first page is always the hardest.": ("Die erste Seite ist immer die schwerste.", "La première page est toujours la plus difficile.", "最初のページがいちばん難しいものです。"),
    "Storyteller": ("Erzähler", "Conteur", "語り手"),
    "Write 10 journal entries.": ("Schreibe 10 Tagebucheinträge.", "Écrivez 10 entrées de journal.", "ジャーナルを10件書く"),
    "Ten entries. Your story is taking shape.": ("Zehn Einträge. Deine Geschichte nimmt Gestalt an.", "Dix entrées. Votre histoire prend forme.", "10件の記録。あなたの物語が形になってきました。"),
    "Chronicler": ("Chronist", "Chroniqueur", "記録者"),
    "Write 30 journal entries.": ("Schreibe 30 Tagebucheinträge.", "Écrivez 30 entrées de journal.", "ジャーナルを30件書く"),
    "Thirty entries of honest reflection.": ("Dreißig Einträge ehrlicher Reflexion.", "Trente entrées de réflexion sincère.", "30件の、正直なふり返り。"),
    "Author of Calm": ("Autor der Ruhe", "Auteur du calme", "穏やかさの作家"),
    "Write 100 journal entries.": ("Schreibe 100 Tagebucheinträge.", "Écrivez 100 entrées de journal.", "ジャーナルを100件書く"),
    "A hundred entries. That's a whole book about you.": ("Hundert Einträge. Das ist ein ganzes Buch über dich.", "Cent entrées. C’est tout un livre sur vous.", "100件の記録。あなたについての1冊の本ができました。"),
    "Thank You": ("Danke", "Merci", "ありがとう"),
    "Write 3 gratitudes.": ("Notiere 3 Dankbarkeitsmomente.", "Notez 3 gratitudes.", "感謝を3つ書く"),
    "Three good things, noticed on purpose.": ("Drei gute Dinge, bewusst wahrgenommen.", "Trois belles choses, remarquées en conscience.", "3つの良いことに、意識して気づきました。"),
    "Grateful Heart": ("Dankbares Herz", "Cœur reconnaissant", "感謝の心"),
    "Write 30 gratitudes.": ("Notiere 30 Dankbarkeitsmomente.", "Notez 30 gratitudes.", "感謝を30個書く"),
    "Thirty reasons to be glad. You found every one.": ("Dreißig Gründe zur Freude. Du hast jeden einzelnen gefunden.", "Trente raisons de se réjouir. Vous les avez toutes trouvées.", "喜べる理由が30個。そのすべてを見つけたのはあなたです。"),
    "Abundance": ("Fülle", "Abondance", "豊かさ"),
    "Write 100 gratitudes.": ("Notiere 100 Dankbarkeitsmomente.", "Notez 100 gratitudes.", "感謝を100個書く"),
    "A hundred gratitudes. Your cup runneth over.": ("Hundert Dankbarkeitsmomente. Dein Becher fließt über.", "Cent gratitudes. Votre coupe déborde.", "100の感謝。心の器があふれています。"),
    "Overflowing": ("Übervoll", "Plénitude", "あふれる感謝"),
    "Write 300 gratitudes.": ("Notiere 300 Dankbarkeitsmomente.", "Notez 300 gratitudes.", "感謝を300個書く"),
    "Three hundred. Gratitude is a habit now.": ("Dreihundert. Dankbarkeit ist jetzt eine Gewohnheit.", "Trois cents. La gratitude est devenue une habitude.", "300個。感謝がもう習慣になっています。"),
    "Day One Done": ("Tag eins geschafft", "Jour 1 réussi", "1日目クリア"),
    "Complete every task on one day of your plan.": ("Erledige alle Aufgaben eines Tages in deinem Plan.", "Terminez toutes les tâches d’une journée de votre plan.", "プランの1日分のタスクをすべて完了"),
    "Day one of your plan, fully done.": ("Tag eins deines Plans, komplett erledigt.", "Premier jour de votre plan, entièrement terminé.", "プランの1日目、すべて完了です。"),
    "First Week Bloom": ("Erste Blüte", "Première floraison", "1週目の花"),
    "Complete 7 days of your plan.": ("Schließe 7 Tage deines Plans ab.", "Terminez 7 jours de votre plan.", "プランの7日分を完了"),
    "A week of your plan, complete. Something's growing.": ("Eine Woche deines Plans geschafft. Etwas wächst.", "Une semaine de votre plan terminée. Quelque chose grandit.", "プランの1週間が完了。何かが育ち始めています。"),
    "Halfway Harbor": ("Halbzeit-Hafen", "Escale à mi-chemin", "折り返しの港"),
    "Complete 15 days of your plan.": ("Schließe 15 Tage deines Plans ab.", "Terminez 15 jours de votre plan.", "プランの15日分を完了"),
    "Halfway there. Look how far you've come.": ("Halbzeit. Sieh nur, wie weit du gekommen bist.", "À mi-chemin. Regardez le chemin parcouru.", "折り返し地点。ここまでの道のりを見てください。"),
    "Plan Complete": ("Plan abgeschlossen", "Plan terminé", "プラン達成"),
    "Complete all 30 days of your plan.": ("Schließe alle 30 Tage deines Plans ab.", "Terminez les 30 jours de votre plan.", "プランの30日間をすべて完了"),
    "Thirty days, start to finish. You did the whole thing.": ("Dreißig Tage, von Anfang bis Ende. Du hast alles geschafft.", "Trente jours, du début à la fin. Vous avez tout accompli.", "30日間、最初から最後まで。すべてやり遂げました。"),
    "Rising Tide": ("Steigende Flut", "Marée montante", "満ちる潮"),
    "Reach level 5.": ("Erreiche Level 5.", "Atteignez le niveau 5.", "レベル5に到達"),
    "Level 5. The tide is rising in your favor.": ("Level 5. Die Flut steigt zu deinen Gunsten.", "Niveau 5. La marée monte en votre faveur.", "レベル5。潮はあなたに味方しています。"),
    "Double Digits": ("Zweistellig", "Deux chiffres", "2ケタ到達"),
    "Reach level 10.": ("Erreiche Level 10.", "Atteignez le niveau 10.", "レベル10に到達"),
    "Level 10. Double digits of calm.": ("Level 10. Zweistellige Ruhe.", "Niveau 10. Le calme à deux chiffres.", "レベル10。落ち着きも2ケタに。"),
    "Rose Gold": ("Roségold", "Or rose", "ローズゴールド"),
    "Reach level 15.": ("Erreiche Level 15.", "Atteignez le niveau 15.", "レベル15に到達"),
    "Rose Gold. Rare air up here.": ("Roségold. Nur wenige kommen so weit.", "Or rose. Peu de gens arrivent jusqu’ici.", "ローズゴールド。ここまで来る人はわずかです。"),
    "Zen Anchor": ("Zen-Anker", "Ancre zen", "禅の錨"),
    "Reach level 20.": ("Erreiche Level 20.", "Atteignez le niveau 20.", "レベル20に到達"),
    "The top rank. Truly anchored.": ("Der höchste Rang. Wirklich verankert.", "Le rang suprême. Un ancrage véritable.", "最高ランク。しっかりと錨を下ろしました。"),
    "Pattern Spotter": ("Musterfinder", "Œil attentif", "パターン発見"),
    "Log 3 different triggers.": ("Erfasse 3 verschiedene Auslöser.", "Notez 3 déclencheurs différents.", "異なるトリガーを3つ記録"),
    "Knowing your triggers takes away their surprise.": ("Wenn du deine Auslöser kennst, verlieren sie ihre Überraschung.", "Connaître vos déclencheurs leur ôte l’effet de surprise.", "トリガーを知れば、不意を突かれなくなります。"),
    "Anchor Friend": ("Anker-Freund", "Ancre amie", "錨の仲間"),
    "Share a CalmAnchor card.": ("Teile eine CalmAnchor-Karte.", "Partagez une carte CalmAnchor.", "CalmAnchorのカードをシェア"),
    "Sharing calm makes more of it.": ("Geteilte Ruhe wird mehr.", "Partager le calme le fait grandir.", "落ち着きは、分かち合うほど増えていきます。"),
    "Calm Ambassador": ("Ruhe-Botschafter", "Ambassadeur du calme", "カーム大使"),
    "Share 5 CalmAnchor cards.": ("Teile 5 CalmAnchor-Karten.", "Partagez 5 cartes CalmAnchor.", "CalmAnchorのカードを5回シェア"),
    "Five shares. Someone out there needed that.": ("Fünfmal geteilt. Irgendwer da draußen hat das gebraucht.", "Cinq partages. Quelqu’un en avait besoin.", "5回のシェア。誰かがきっと必要としていました。"),
    "Night Watch": ("Nachtwache", "Veille de nuit", "夜の見張り"),
    "Finish a Panic SOS session between midnight and 5 a.m.": ("Beende eine Panic-SOS-Sitzung zwischen Mitternacht und 5 Uhr.", "Terminez une séance Panic SOS entre minuit et 5 h.", "午前0時から5時の間にPanic SOSセッションを完了"),
    "You got through the small hours. Be gentle with yourself today.": ("Du hast die frühen Morgenstunden überstanden. Sei heute sanft zu dir.", "Vous avez traversé la nuit. Prenez soin de vous aujourd’hui.", "真夜中を乗り越えました。今日は自分にやさしくしてください。"),
    "Early Light": ("Frühes Licht", "Première lueur", "朝の光"),
    "Check in before 7 a.m.": ("Mach vor 7 Uhr einen Check-in.", "Faites un bilan avant 7 h.", "午前7時前にチェックイン"),
    "Up with the sun and already checking in.": ("Mit der Sonne aufgestanden und schon eingecheckt.", "Debout avec le soleil, et déjà votre bilan.", "朝日とともに起きて、もうチェックイン。"),
    "Welcome Back": ("Willkommen zurück", "Bon retour", "おかえりなさい"),
    "Come back after a week away.": ("Komm nach einer Woche Pause zurück.", "Revenez après une semaine d’absence.", "1週間ぶりに戻ってくる"),
    "Welcome back. Returning is the bravest part.": ("Willkommen zurück. Zurückzukommen ist das Mutigste.", "Bon retour. Revenir, c’est le plus courageux.", "おかえりなさい。戻ってくることこそ、いちばん勇気のいることです。"),
    "Saved by Grace": ("Schonfrist", "Jour de grâce", "猶予の一日"),
    "Let a grace day save your streak.": ("Lass einen Schontag deine Serie retten.", "Laissez un jour de grâce sauver votre série.", "猶予日で連続記録を守る"),
    "One missed day didn't undo your progress. Grace works.": ("Ein verpasster Tag macht deinen Fortschritt nicht zunichte. Der Schontag wirkt.", "Un jour manqué n’a pas effacé vos progrès. Le jour de grâce a fait son effet.", "1日休んでも、進歩は消えません。猶予日が役立ちました。"),

    # Anchor Pass tiers
    "Sea Glass": ("Meerglas", "Verre de mer", "シーグラス"),
    "Bronze": ("Bronze", "Bronze", "ブロンズ"),
    "Silver": ("Silber", "Argent", "シルバー"),
    "Gold": ("Gold", "Or", "ゴールド"),
    "Pearl": ("Perle", "Perle", "パール"),

    # Ranks
    "First Breath": ("Erster Atemzug", "Premier souffle", "最初の一息"),
    "Wave Watcher": ("Wellenbeobachter", "Guetteur de vagues", "波の観察者"),
    "Tide Learner": ("Gezeitenschüler", "Apprenti des marées", "潮の見習い"),
    "Steady Swimmer": ("Ruhiger Schwimmer", "Nageur serein", "落ち着いた泳ぎ手"),
    "Harbor Seeker": ("Hafensucher", "En quête du port", "港を探す人"),
    "Calm Sailor": ("Ruhiger Segler", "Marin serein", "穏やかな船乗り"),
    "Deep Breather": ("Tiefatmer", "Souffle profond", "深く呼吸する人"),
    "Grounded": ("Geerdet", "Enraciné", "地に足つけて"),
    "Steady Keel": ("Ruhiger Kiel", "Quille stable", "揺るがぬ竜骨"),
    "Lighthouse Keeper": ("Leuchtturmwärter", "Gardien du phare", "灯台守"),
    "Storm Walker": ("Sturmwanderer", "Marcheur des tempêtes", "嵐を歩む人"),
    "Calm Captain": ("Ruhiger Kapitän", "Capitaine serein", "穏やかな船長"),
    "Still Waters": ("Stille Wasser", "Eaux calmes", "静かな水面"),
    "Safe Harbor": ("Sicherer Hafen", "Havre de paix", "安らぎの港"),
    "Anchor Bearer": ("Ankerträger", "Porteur d’ancre", "錨を担う人"),
    "True North": ("Wahrer Norden", "Vrai Nord", "真の北"),
    "Deep Calm": ("Tiefe Ruhe", "Calme profond", "深い静けさ"),
    "Tide Master": ("Gezeitenmeister", "Maître des marées", "潮の達人"),
    "Anchor Sage": ("Ankerweiser", "Sage de l’ancre", "錨の賢者"),
    "Every calm breath counts. You're finding your rhythm.": ("Jeder ruhige Atemzug zählt. Du findest deinen Rhythmus.", "Chaque souffle calme compte. Vous trouvez votre rythme.", "穏やかな呼吸のひとつひとつが大切です。自分のリズムが見つかってきました。"),
    "You keep showing up. That's how calm becomes a habit.": ("Du bleibst dran. So wird Ruhe zur Gewohnheit.", "Vous êtes toujours là. C’est ainsi que le calme devient une habitude.", "続けてここに来ていますね。そうして落ち着きは習慣になります。"),
    "Waves still come. You know how to ride them now.": ("Wellen kommen noch immer. Jetzt weißt du, wie du sie reitest.", "Les vagues viennent encore. Vous savez maintenant les surfer.", "波はまだ来ます。でも今は乗りこなし方を知っています。"),
    "Steady hands on the wheel. Look how far you've sailed.": ("Ruhige Hände am Steuer. Sieh nur, wie weit du gesegelt bist.", "Des mains sûres à la barre. Regardez la distance parcourue.", "舵を握る手は揺るぎません。こんなに遠くまで来ました。"),
    "Calm isn't luck anymore. It's a skill you've built.": ("Ruhe ist kein Glück mehr. Sie ist eine Fähigkeit, die du aufgebaut hast.", "Le calme n’est plus une question de chance. C’est une compétence que vous avez bâtie.", "落ち着きはもう偶然ではありません。あなたが築いたスキルです。"),
    "Rare, hard-won and entirely yours.": ("Selten, hart erarbeitet und ganz deins.", "Rare, durement gagné et entièrement à vous.", "希少で、努力で勝ち取った、あなただけのもの。"),

    # Achievements screen / sharing
    "Double-tap to share your rank": ("Doppeltippen, um deinen Rang zu teilen", "Touchez deux fois pour partager votre rang", "ダブルタップしてランクをシェア"),
    "Badges": ("Abzeichen", "Badges", "バッジ"),
    "Enjoying CalmAnchor? Leave a review on the App Store": ("Gefällt dir CalmAnchor? Schreib eine Bewertung im App Store", "Vous aimez CalmAnchor ? Laissez un avis sur l’App Store", "CalmAnchorを気に入っていただけましたか？App Storeでレビューをお願いします"),
    "Achievements": ("Erfolge", "Succès", "実績"),
    "Share your rank": ("Teile deinen Rang", "Partagez votre rang", "ランクをシェア"),
    "My calm rank: %@.": ("Mein Ruhe-Rang: %@.", "Mon rang de calme : %@.", "私のカームランク：%@。"),
    "Next badge": ("Nächstes Abzeichen", "Prochain badge", "次のバッジ"),
    "It happens when it happens. Keep going.": ("Es passiert, wenn es passiert. Mach weiter.", "Ça viendra en temps voulu. Continuez.", "その時は自然にやってきます。続けていきましょう。"),
    "Earned %@": ("Erhalten am %@", "Obtenu le %@", "%@に獲得"),
    "%lld of %lld": ("%lld von %lld", "%lld sur %lld", "%lld／%lld"),
    "Premium feature": ("Premium-Funktion", "Fonctionnalité Premium", "プレミアム機能"),
    "I just unlocked %@ in CalmAnchor.": ("Ich habe gerade %@ in CalmAnchor freigeschaltet.", "Je viens de débloquer %@ dans CalmAnchor.", "CalmAnchorで「%@」を獲得しました。"),
    "Show it off": ("Zeig es her", "Montrez-le", "みんなに見せる"),
    "+%lld more badges": ("+%lld weitere Abzeichen", "+%lld autres badges", "ほか%lld個のバッジ"),
    "Share": ("Teilen", "Partager", "シェア"),
    "LEVEL %lld": ("LEVEL %lld", "NIVEAU %lld", "レベル %lld"),
    "Secret badge found": ("Geheimes Abzeichen entdeckt", "Badge secret découvert", "シークレットバッジ発見"),
    "Badge unlocked": ("Abzeichen freigeschaltet", "Badge débloqué", "バッジ獲得"),
    "New rank": ("Neuer Rang", "Nouveau rang", "新しいランク"),
    "Calm streak": ("Ruhe-Serie", "Série de calme", "連続記録"),
    "Friend": ("Freund", "Ami·e", "フレンド"),
    "Thirty days. This isn't luck anymore — it's who you are now.": ("Dreißig Tage. Das ist kein Glück mehr – das bist jetzt du.", "Trente jours. Ce n’est plus de la chance – c’est ce que vous êtes, désormais.", "30日。もう偶然ではありません — これが今のあなたです。"),
    "+%lld XP": ("+%lld XP", "+%lld XP", "+%lld XP"),
    "%lld days of calm in CalmAnchor.": ("%lld Tage Ruhe mit CalmAnchor.", "%lld jours de calme avec CalmAnchor.", "CalmAnchorで%lld日間の穏やかさ。"),
    "Panic attack help · Free on the App Store": ("Hilfe bei Panikattacken · Kostenlos im App Store", "Aide contre les crises de panique · Gratuit sur l’App Store", "パニック発作のサポート · App Storeで無料"),
    "What's your calm rank?": ("Was ist dein Ruhe-Rang?", "Quel est votre rang de calme ?", "あなたのカームランクは？"),
    "My calm rank": ("Mein Ruhe-Rang", "Mon rang de calme", "私のカームランク"),
    "level": ("Level", "niveau", "レベル"),
    "day streak": ("Tage in Folge", "jours de série", "日連続"),
    "badges": ("Abzeichen", "badges", "バッジ"),
    "Calm is a skill. I'm practicing.": ("Ruhe ist eine Fähigkeit. Ich übe sie.", "Le calme s’apprend. Je m’entraîne.", "落ち着きはスキル。練習中です。"),
    "days of choosing calm": ("Tage, an denen ich Ruhe gewählt habe", "jours à choisir le calme", "日間、落ち着きを選んできました"),
    "One breath at a time.": ("Ein Atemzug nach dem anderen.", "Une respiration à la fois.", "ひと呼吸ずつ。"),

    # Weekly recap
    "Next": ("Weiter", "Suivant", "次へ"),
    "Previous": ("Zurück", "Précédent", "前へ"),
    "Your week in calm": ("Deine Woche in Ruhe", "Votre semaine de calme", "あなたの穏やかな1週間"),
    "Your week\nin calm": ("Deine Woche\nin Ruhe", "Votre semaine\nde calme", "あなたの\n穏やかな1週間"),
    "Seven days. Let's look at what you did.": ("Sieben Tage. Schauen wir, was du geschafft hast.", "Sept jours. Voyons ce que vous avez accompli.", "7日間。あなたの歩みをふり返りましょう。"),
    "calm session": ("Ruhe-Sitzung", "séance de calme", "回のセッション"),
    "calm sessions": ("Ruhe-Sitzungen", "séances de calme", "回のセッション"),
    "%lld minutes of breathing through it.": ("%lld Minuten bewusstes Durchatmen.", "%lld minutes à respirer pour passer le cap.", "%lld分間、呼吸で乗り越えました。"),
    "Average intensity": ("Durchschnittliche Intensität", "Intensité moyenne", "平均の強さ"),
    "before": ("vorher", "avant", "前"),
    "after": ("nachher", "après", "後"),
    "Your mood this week": ("Deine Stimmung diese Woche", "Votre humeur cette semaine", "今週の気分"),
    "%lld check-ins. You kept noticing.": ("%lld Check-ins. Du bist aufmerksam geblieben.", "%lld bilans. Toujours à l’écoute de vous-même.", "%lld回のチェックイン。気づき続けました。"),
    "New this week": ("Neu diese Woche", "Nouveau cette semaine", "今週の新着"),
    "One new badge. Well earned.": ("Ein neues Abzeichen. Wohlverdient.", "Un nouveau badge. Bien mérité.", "新しいバッジが1つ。よく頑張りました。"),
    "%lld new badges. Well earned.": ("%lld neue Abzeichen. Wohlverdient.", "%lld nouveaux badges. Bien mérités.", "新しいバッジが%lld個。よく頑張りました。"),
    "That was your week.": ("Das war deine Woche.", "Voilà votre semaine.", "これがあなたの1週間でした。"),
    "sessions": ("Sitzungen", "séances", "セッション"),
    "check-ins": ("Check-ins", "bilans", "チェックイン"),
    "new badges": ("neue Abzeichen", "nouveaux badges", "新バッジ"),
    "Share my week": ("Meine Woche teilen", "Partager ma semaine", "1週間をシェア"),
    "Play again": ("Nochmal abspielen", "Revoir", "もう一度見る"),
    "Big drops. Your tools are working.": ("Große Rückgänge. Deine Werkzeuge wirken.", "De fortes baisses. Vos outils fonctionnent.", "大きく下がりました。あなたの方法が効いています。"),
    "Every session brought it down.": ("Jede Sitzung hat sie gesenkt.", "Chaque séance l’a fait baisser.", "どのセッションでも下がりました。"),
    "You stayed with it. That counts.": ("Du bist drangeblieben. Das zählt.", "Vous avez tenu bon. Ça compte.", "続けられました。それが大切です。"),
    "My week in calm: %lld sessions, %lld check-ins.": ("Meine Woche in Ruhe: %lld Sitzungen, %lld Check-ins.", "Ma semaine de calme : %lld séances, %lld bilans.", "私の穏やかな1週間：セッション%lld回、チェックイン%lld回。"),
    "Mood by day": ("Stimmung pro Tag", "Humeur par jour", "日ごとの気分"),
    "My week in calm": ("Meine Woche in Ruhe", "Ma semaine de calme", "私の穏やかな1週間"),
    "NEW": ("NEU", "NOUVEAU", "NEW"),
    "Opens your badges and rank": ("Öffnet deine Abzeichen und deinen Rang", "Ouvre vos badges et votre rang", "バッジとランクを開きます"),
    "Your recap is ready": ("Dein Rückblick ist fertig", "Votre récap est prêt", "振り返りの準備ができました"),
    "Sessions, moods and wins from the last 7 days": ("Sitzungen, Stimmungen und Erfolge der letzten 7 Tage", "Séances, humeurs et réussites des 7 derniers jours", "過去7日間のセッション、気分、達成"),
}
